### ISSUE TITLE
Can't override default extensions option

### ISSUE THREAD

**Issue by iMuFeng** [surmon-china/vue-codemirror#167]
### Clear and concise description of the problem

Can't override default extensions option

### Suggested solution

Replace `basicSetup` with `minimalSetup` or set the default extensions to `[]`

https://github.com/surmon-china/vue-codemirror/blob/222b5c685fc006a8ccd5c834f588589c7f58edc3/src/config.ts#L2

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by surmon-china** [comment]
Actually, you can specify the default extensions as `[]` or `[minimalSetup]` by means of a global installation.

https://github.com/surmon-china/vue-codemirror#basic-setup

**Comment by kabalage** [comment]
But what if I don't want to install it globally? I don't even want to import codemirror on page load, only when it's needed.

Solution 1: Add a `useBasicSetup` (or similarily named) prop to the component with default value of `true` to not break existing code. Handling reactivity for this would cause complications. But personally I would not mind if this prop wasn't handled reactively.

Solution 2: Expose the config injection symbol to be able to provide the "global" config in wrapper components. It's uglier, but less expected to be reactive this way.

**Comment by kabalage** [comment]
Do you prefer any of the solutions above? I would be happy to make a PR if we decide on the way to go.

**Comment by surmon-china** [comment]
Hi! @kabalage 

Thanks for your feedback, it's a valuable question.

If an API like `useBasicSetup` is exposed, this will be coupled with a specific module like `basicSetup` and users will likely want to use `miniSetup` or possibly `xxxSetup` as defaultExtensions in the future, something like `useBasicSetup` has the disadvantage of growing with the uncertainty of external dependencies.

As a public component, the focus should be on exposing public capabilities similar to defaultExtensions, which would allow for more flexible reusability with the addition of new interfaces.

I'm considering possibly adding an API like `defaultExtensions`, but it should try to avoid naming conflicts with existing `extensions` and be able to express its semantics accurately.

I'll have a definitive solution soon, so stay tuned!

**Comment by surmon-china** [comment]
@kabalage 

My proposal is.

1. I will add `basicExtensions` API to the component's props for passing basic extensions.

2. `extensions` in the original global default config will be deprecated due to incorrect semantics and will be renamed to `basicExtensions`.

3. The documentation will fix the incorrect interpretation of the current `extensions` and add the `basicExtensions` API.

The priority of component consumption `basicExtensions` is:
1. `props.basicExtensions`
2. `useGlobalConfig().basicExtensions`
3. `DEFAULT_CONFIG.basicExtensions`

What do you think?

**Comment by kabalage** [comment]
I think your proposed solution could also work, but I think passing extensions in two props is a bit more confusing than my first suggestion. What I meant by `useBasicSetup` is a way to opt out of using the defaults, which is the `basicSetup`. I get that the wording can be misleading and someone could think that there must be a `useMinimalSetup` as well, so I propose the prop `useDefaultExtensions: boolean`. When someone wants to use e.g. `minimalSetup` or any customized setup, they could opt out of the default way by setting `useDefaultExtensions` to `false` and they could set the `extensions` to whatever they want. 

I also checked [uiwjs/react-codemirror](https://github.com/uiwjs/react-codemirror) and they chose a similar way. They added the following prop:

```
basicSetup?: boolean | BasicSetupOptions;
```

Where `BasicSetupOptions` is:

```ts
interface BasicSetupOptions {
  lineNumbers?: boolean;
  highlightActiveLineGutter?: boolean;
  highlightSpecialChars?: boolean;
  history?: boolean;
  foldGutter?: boolean;
  drawSelection?: boolean;
  dropCursor?: boolean;
  allowMultipleSelections?: boolean;
  indentOnInput?: boolean;
  syntaxHighlighting?: boolean;
  bracketMatching?: boolean;
  closeBrackets?: boolean;
  autocompletion?: boolean;
  rectangularSelection?: boolean;
  crosshairCursor?: boolean;
  highlightActiveLine?: boolean;
  highlightSelectionMatches?: boolean;
  closeBracketsKeymap?: boolean;
  defaultKeymap?: boolean;
  searchKeymap?: boolean;
  historyKeymap?: boolean;
  foldKeymap?: boolean;
  completionKeymap?: boolean;
  lintKeymap?: boolean;
}
```

I don't know how much of a goal of this library to be similar to the react version though. I think the `boolean` prop would suffice.

So my proposal is:

1. Add new `useDefaultExtensions: boolean` (or match the react library's terminology `basicSetup` to allow better cross-compatible knowledge) Use the default value of `true` to not break previous usage.
2. Deprecate the global config `extensions` and add `defaultExtensions`. (The global `extensions` would work the same as `defaultExtensions` for a while when the latter is not defined)
3. The extensions would be computed from the props: `useDefaultExtensions`, `extensions` and the global config `defaultExtensions` (which by default is the `basicSetup`). The `defaultExtensions` would not be added when the prop `useDefaultExtensions` is false.

Maybe the word "default" is still not the best choice because it could also suggest that the `extensions` prop is overriding the "defaults" so maybe `useBaseExtensions` prop and `baseExtensions` global? (deliberately not `basic`).

Of course it's your project, so you don't have to agree with me. 🙂 Your proposal is also good for me as it's fixing my problem.

**Comment by kabalage** [comment]
Do you have any thoughts on the above? Do you need anything to get this going?

**Comment by surmon-china** [comment]
Hi @kabalage 

Sorry for the late reply.

It's true that creating a redundant concept is not elegant and can be ambiguous, but I need to confirm the difference between `props.extensions` and `basicExtensions`, which are consumed by [passing `EditorState.create({ extensions })`](https://github.com/surmon-china/vue-codemirror/blob/main/src/component.ts#L42) which may be contradictory to vue's responsiveness, so it is not certain that `basicExtensions` is a concept that can be ignored.

**Comment by tobihanl** [comment]
Hi @surmon-china @kabalage,

is there any update on this issue? I really like vue-codemirror so far but the fact that basicSetup is always included makes it hard to integrate with some other extensions. Is there a specific reason why this is the default instead of just an empty extension array? For now, I had to fork this repo and remove basicSetup from the default config.

I feel like since it is so easy to include basicSetup, there is not really a need to have it in this library by default anyways and the easiest solution would be to just remove it.

What do you think?

**Comment by francisashley** [comment]
I agree with @tobihanl, basicSetup should be opt-in and included in the README code example.
