### ISSUE TITLE
How to load codemirror when is hidden behind a tab

### ISSUE THREAD

**Issue by microcipcip** [surmon-china/vue-codemirror#61]
If codemirror is inside a tab, when you click the tab, by default it won't load. Fix as follows:

```
<tabs>
  <tab @click="refreshCodemirror">
    <codemirror
      ref="codeMirrorField1"
      v-model="field"
      :options="cmOptions" />
  </tab>
  <tab @click="refreshCodemirror">
    <codemirror
      ref="codeMirrorField2"
      v-model="field"
      :options="cmOptions" />
  </tab>
</tabs>
  
import Vue from 'vue'

export default {
  methods: {
    refreshCodemirror () {
      Vue.nextTick(() => {
        for (const $ref in this.$refs) {
          if (this.$refs[$ref].hasOwnProperty('codemirror')) {
            this.$refs[$ref].codemirror.refresh() // IMPORTANT CODE HERE
          }
        }
      })
    }
  }
}
```

**Comment by kickthemooon** [comment]
I had to add `this.$refs[$ref][0]`, not sure whats the reason.

**Comment by mbitzos** [comment]
I'm running into this same issue, and attempted to use your solution, but I am not able to get @click to trigger on tab click. What tabs component are you using, because I am using UIV's bootstrap 3 vue components and cannot hook into the on click event which means i can tell code mirror to refresh at the instance of the tab loading ever.

**Comment by surmon-china** [comment]
Try to use `v-if` to control component re-rendering when the container's explicit state is switched, or manually call the component's `refresh` method.

**Comment by antbaobao** [comment]
@surmon-china thx

**Comment by Calvinchen-FE** [comment]
Initially display it but set the opacity to 0

**Comment by zedee** [comment]
@Pedrat I also had this issue and I'm using Vuetify tabs as well.

The architecture of my application makes a bit cumbersome to "communicate" to children component the active tab (because I have lots of tabs and sub-tabs), and make conditional re-render so this alternative solution worked for me.

From official docs: https://codemirror.net/doc/manual.html#addon_autorefresh
From Stack Overflow: https://stackoverflow.com/questions/8349571/codemirror-editor-is-not-loading-content-until-clicked

You will need to add in your component file the following line before the `export default { ... }` :
```
import "codemirror/addon/display/autorefresh.js";
```

And then into your `cmOptions`, add this key/value: 
```
autoRefresh: true
```

It worked for me, so it should for you as well!

**Comment by Pedrat** [comment]
Thanks @zedee ! It worked like a charm!

**Comment by obedparla** [comment]
> autoRefresh: true

I was seeing the content show after the tab, which looked ugly. By making the auto refresh polling faster, it looks like the text was always there. The default is 250ms, instead 50ms worked for me.

```
autoRefresh: { delay: 50 }
```
